language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

services:
  - apc
  - memcache
  - memcached
  - redis-server

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then pecl channel-update pecl.php.net; fi;
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then echo yes | pecl install apcu-4.0.10; fi;
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo "apc.enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer --prefer-source install

script:
  - ./vendor/bin/phpunit
